apiVersion: v1
kind: Service
metadata:
  name: rio-api
spec:
  selector: { app: rio-api } # sélectionne stable ET canary — Istio fait la distinction, pas ce Service
  ports:
    - { port: 80, targetPort: 8080 }
