apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels: { app: {{ .Release.Name }}-api }
  template:
    metadata:
      labels: { app: {{ .Release.Name }}-api }
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports: [{ containerPort: 8080 }]
          env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: {{ .Values.secrets.name }}, key: database-url } }
            - name: RABBITMQ_URL
              valueFrom: { secretKeyRef: { name: {{ .Values.secrets.name }}, key: rabbitmq-url } }
            - name: REDIS_URL
              value: "{{ .Values.redis.url | default "demo-redis-master:6379" }}"
            - name: S3_BUCKET
              value: "{{ .Values.s3.bucket }}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom: { secretKeyRef: { name: {{ .Values.secrets.name }}, key: aws-access-key-id, optional: true } }
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: {{ .Values.secrets.name }}, key: aws-secret-access-key, optional: true } }
            - name: AWS_SESSION_TOKEN
              valueFrom: { secretKeyRef: { name: {{ .Values.secrets.name }}, key: aws-session-token, optional: true } }
            - name: AWS_REGION
              value: "{{ .Values.s3.region | default "us-east-1" }}"
