# -*- coding: utf-8 -*-
# Adaptations multilingues (EN/ES/PT-BR) — partie 2/4

DATA_PART2 = [
{
"name": "Biblioteca Nacional do Brasil",
"fr": "Sur la Cinelândia, cet imposant édifice de 1910 abrite la plus grande bibliothèque d'Amérique latine : des millions de volumes, dont des manuscrits et des livres rarissimes hérités de la couronne portugaise. Son architecture éclectique, mêlant néoclassique et art nouveau, s'orne d'œuvres de Visconti et Bernardelli.",
"en": "On Cinelândia square, this imposing nineteen-ten building holds the largest library in Latin America: millions of volumes, including manuscripts and rare books inherited from the Portuguese crown. Its eclectic architecture, blending neoclassical and art nouveau, is adorned with works by Visconti and Bernardelli.",
"es": "En la Cinelândia, este imponente edificio de mil novecientos diez alberga la biblioteca más grande de América Latina: millones de volúmenes, incluyendo manuscritos y libros rarísimos heredados de la corona portuguesa. Su arquitectura ecléctica, que combina neoclásico y art nouveau, se adorna con obras de Visconti y Bernardelli.",
"pt": "Na Cinelândia, esse imponente prédio de mil novecentos e dez abriga a maior biblioteca da América Latina: milhões de volumes, incluindo manuscritos e livros raríssimos herdados da coroa portuguesa. Sua arquitetura eclética, misturando neoclássico e art nouveau, é adornada com obras de Visconti e Bernardelli.",
},
{
"name": "Casa de Rui Barbosa",
"fr": "Cette élégante demeure néoclassique de Botafogo, à la façade marquée par un fronton triangulaire et des vérandas en fer, fut la maison de Rui Barbosa, juriste et homme politique majeur du Brésil. Conservée avec son mobilier et son immense bibliothèque, elle plonge le visiteur dans l'intérieur bourgeois de la fin du XIXe siècle. Un musée-maison intime.",
"en": "This elegant neoclassical house in Botafogo, its façade marked by a triangular pediment and iron verandas, was the home of Rui Barbosa, a major Brazilian jurist and statesman. Preserved with its furniture and vast library, it takes visitors inside a late-nineteenth-century upper-class home. An intimate house museum.",
"es": "Esta elegante mansión neoclásica de Botafogo, con su fachada marcada por un frontón triangular y verandas de hierro, fue la casa de Rui Barbosa, jurista y político brasileño de gran importancia. Conservada con su mobiliario y su enorme biblioteca, sumerge al visitante en un interior burgués de fines del siglo diecinueve. Un museo-casa íntimo.",
"pt": "Essa elegante casa neoclássica de Botafogo, com fachada marcada por um frontão triangular e varandas de ferro, foi o lar de Rui Barbosa, jurista e político de peso no Brasil. Preservada com seu mobiliário e sua imensa biblioteca, ela leva o visitante para dentro de um interior burguês do final do século dezenove. Um museu-casa intimista.",
},
{
"name": "Catedral Metropolitana de São Sebastião",
"fr": "Ce cône de béton de 75 mètres, c'est la cathédrale de Saint-Sébastien, patron de Rio. Élevée entre 1964 et 1979 dans un style résolument moderne, elle peut accueillir vingt mille personnes debout. À l'intérieur, quatre immenses vitraux montent du sol jusqu'à la coupole et baignent l'espace d'une lumière colorée. Une allure de pyramide au cœur de la ville.",
"en": "This seventy-five-meter concrete cone is the cathedral of Saint Sebastian, Rio's patron saint. Built between nineteen sixty-four and nineteen seventy-nine in a strikingly modern style, it can hold twenty thousand people standing. Inside, four huge stained-glass windows rise from floor to dome, bathing the space in colored light. A pyramid-shaped landmark at the heart of the city.",
"es": "Este cono de concreto de setenta y cinco metros es la catedral de San Sebastián, patrono de Río. Construida entre mil novecientos sesenta y cuatro y mil novecientos setenta y nueve en un estilo marcadamente moderno, puede albergar a veinte mil personas de pie. En su interior, cuatro enormes vitrales suben desde el suelo hasta la cúpula, bañando el espacio con una luz de colores. Una silueta de pirámide en el corazón de la ciudad.",
"pt": "Esse cone de concreto de setenta e cinco metros é a catedral de São Sebastião, padroeiro do Rio. Erguida entre mil novecentos e sessenta e quatro e mil novecentos e setenta e nove em estilo bem moderno, ela comporta vinte mil pessoas em pé. Por dentro, quatro vitrais enormes sobem do chão até a cúpula e banham o espaço com uma luz colorida. Uma silhueta de pirâmide no coração da cidade.",
},
{
"name": "Convento de Santo Antônio",
"fr": "Perché sur sa colline au Largo da Carioca, ce couvent franciscain est l'un des plus anciens ensembles coloniaux de Rio. Les cariocas y viennent prier saint Antoine. À côté, l'église de São Francisco da Penitência complète l'ensemble.",
"en": "Perched on its hill above Largo da Carioca, this Franciscan convent is one of the oldest colonial ensembles in Rio. Local cariocas come here to pray to Saint Anthony. Right next door, the church of São Francisco da Penitência completes the ensemble.",
"es": "Encaramado en su colina sobre el Largo da Carioca, este convento franciscano es uno de los conjuntos coloniales más antiguos de Río. Los cariocas vienen aquí a orar a San Antonio. Al lado, la iglesia de São Francisco da Penitência completa el conjunto.",
"pt": "No alto da colina do Largo da Carioca, esse convento franciscano é um dos mais antigos conjuntos coloniais do Rio. Os cariocas vêm aqui rezar para Santo Antônio. Ao lado, a igreja de São Francisco da Penitência completa o conjunto.",
},
{
"name": "Estádio Jornalista Mário Filho",
"fr": "Temple du football brésilien, le Maracanã fut construit pour la Coupe du monde de 1950. Il a accueilli la finale de 2014 comme les Jeux de 2016. Même vide, l'immense ovale impressionne ; un jour de match, c'est une marée de chants et de tambours. Le cœur battant de la passion carioca.",
"en": "The temple of Brazilian football, the Maracanã was built for the nineteen-fifty World Cup. It hosted both the twenty-fourteen World Cup final and the twenty-sixteen Olympics. Even empty, the huge oval is impressive; on match day, it's a sea of chanting and drums. The beating heart of carioca passion.",
"es": "Templo del fútbol brasileño, el Maracanã fue construido para el Mundial de mil novecientos cincuenta. Albergó tanto la final del Mundial de dos mil catorce como los Juegos Olímpicos de dos mil dieciséis. Incluso vacío, el enorme óvalo impresiona; un día de partido es una marea de cánticos y tambores. El corazón palpitante de la pasión carioca.",
"pt": "Templo do futebol brasileiro, o Maracanã foi construído para a Copa do Mundo de mil novecentos e cinquenta. Recebeu tanto a final da Copa de dois mil e quatorze quanto os Jogos Olímpicos de dois mil e dezesseis. Mesmo vazio, o imenso oval impressiona; num dia de jogo, é um mar de cânticos e tambores. O coração pulsante da paixão carioca.",
},
{
"name": "Fortaleza de São João",
"fr": "À la pointe d'Urca, gardant l'entrée de la baie, cette forteresse est l'un des plus anciens sites militaires du Brésil : c'est tout près d'ici que la ville fut fondée en 1565. Encore occupée par l'armée, elle se visite pour son histoire, ses canons et sa vue rapprochée sur le Pain de Sucre.",
"en": "At the tip of Urca, guarding the entrance to the bay, this fortress is one of Brazil's oldest military sites: the city was founded just nearby in fifteen sixty-five. Still occupied by the army, it can be visited for its history, its cannons, and its close-up view of Sugarloaf Mountain.",
"es": "En la punta de Urca, custodiando la entrada de la bahía, esta fortaleza es uno de los sitios militares más antiguos de Brasil: la ciudad fue fundada muy cerca de aquí en mil quinientos sesenta y cinco. Todavía ocupada por el ejército, se puede visitar por su historia, sus cañones y su vista cercana del Pan de Azúcar.",
"pt": "Na ponta de Urca, guardando a entrada da baía, essa fortaleza é um dos sítios militares mais antigos do Brasil: a cidade foi fundada bem pertinho daqui, em mil quinhentos e sessenta e cinco. Ainda ocupada pelo exército, ela pode ser visitada por sua história, seus canhões e sua vista de perto do Pão de Açúcar.",
},
{
"name": "Forte de Copacabana",
"fr": "À la pointe sud de la plage de Copacabana, ce fort militaire de 1914 fut bâti pour empêcher les navires de guerre d'approcher la capitale par la mer ouverte. On visite ses canons et ses casemates, mais on vient surtout pour la vue : de la terrasse, tout l'arc de sable de Copacabana se déploie jusqu'au Pain de Sucre. Un café face à l'océan clôt la promenade.",
"en": "At the southern tip of Copacabana beach, this nineteen-fourteen military fort was built to keep warships from approaching the capital from the open sea. Visitors come for the cannons and bunkers, but mostly for the view: from the terrace, the whole sandy arc of Copacabana unfolds all the way to Sugarloaf Mountain. A café facing the ocean rounds off the visit.",
"es": "En el extremo sur de la playa de Copacabana, este fuerte militar de mil novecientos catorce fue construido para impedir que los buques de guerra se acercaran a la capital por mar abierto. Se visitan sus cañones y casamatas, pero se viene sobre todo por la vista: desde la terraza, todo el arco de arena de Copacabana se despliega hasta el Pan de Azúcar. Un café frente al océano cierra el paseo.",
"pt": "Na ponta sul da praia de Copacabana, esse forte militar de mil novecentos e catorze foi construído para impedir que navios de guerra se aproximassem da capital pelo mar aberto. Visitam-se seus canhões e casamatas, mas a gente vem mesmo é pela vista: do terraço, todo o arco de areia de Copacabana se estende até o Pão de Açúcar. Um café de frente para o oceano fecha o passeio.",
},
{
"name": "Igreja da Candelária",
"fr": "Sa grande coupole domine le centre depuis le XIXe siècle. Commencée en 1775 sur l'emplacement d'une chapelle plus ancienne, la Candelária mêle façade baroque et intérieur richement décoré de marbres importés d'Europe. C'est aussi un lieu de mémoire : devant ses marches, une plaque rappelle le massacre d'enfants des rues de 1993. Beauté et gravité mêlées.",
"en": "Its great dome has towered over downtown since the nineteenth century. Begun in seventeen seventy-five on the site of an older chapel, Candelária combines a baroque façade with an interior richly decorated in marble imported from Europe. It's also a place of memory: on its steps, a plaque recalls the massacre of street children in nineteen ninety-three. Beauty and gravity intertwined.",
"es": "Su gran cúpula domina el centro desde el siglo diecinueve. Iniciada en mil setecientos setenta y cinco sobre el emplazamiento de una capilla más antigua, la Candelária combina una fachada barroca con un interior ricamente decorado con mármoles importados de Europa. Es también un lugar de memoria: frente a sus escalinatas, una placa recuerda la masacre de niños de la calle de mil novecientos noventa y tres. Belleza y gravedad entrelazadas.",
"pt": "Sua grande cúpula domina o centro desde o século dezenove. Iniciada em mil setecentos e setenta e cinco no lugar de uma capela mais antiga, a Candelária mistura fachada barroca e interior ricamente decorado com mármores importados da Europa. É também um lugar de memória: em frente às suas escadarias, uma placa lembra a chacina de crianças de rua de mil novecentos e noventa e três. Beleza e gravidade misturadas.",
},
{
"name": "Igreja da Glória do Outeiro",
"fr": "Juchée sur une colline dominant la baie, cette église baroque du XVIIIe siècle, de plan octogonal, était la préférée de la famille impériale. Ses azulejos portugais et sa silhouette élégante en font l'une des plus charmantes de Rio. La montée se récompense d'une jolie vue sur le Flamengo.",
"en": "Perched on a hill overlooking the bay, this octagonal, eighteenth-century baroque church was the imperial family's favorite. Its Portuguese azulejo tiles and elegant silhouette make it one of the most charming in Rio. The climb up is rewarded with a lovely view over Flamengo.",
"es": "Encaramada en una colina que domina la bahía, esta iglesia barroca del siglo dieciocho, de planta octogonal, era la preferida de la familia imperial. Sus azulejos portugueses y su silueta elegante la convierten en una de las más encantadoras de Río. La subida se recompensa con una hermosa vista sobre Flamengo.",
"pt": "No alto de uma colina com vista para a baía, essa igreja barroca do século dezoito, de planta octogonal, era a preferida da família imperial. Seus azulejos portugueses e sua silhueta elegante fazem dela uma das mais charmosas do Rio. A subida é recompensada com uma bela vista do Flamengo.",
},
{
"name": "Igreja da Ordem Terceira do Carmo",
"fr": "Voisine de l'ancienne cathédrale sur la Praça XV, cette église de la confrérie du Carmel cache un intérieur baroque d'une grande richesse : talha dorée, retables ouvragés et une nef ornée avec faste. Les deux églises du Carmo, côte à côte, forment l'un des ensembles religieux les plus précieux du centre historique.",
"en": "Next to the former cathedral on Praça XV, this church of the Carmelite brotherhood hides a lavish baroque interior: gilded talha woodwork, ornate altarpieces, and a nave decorated with great splendor. The two Carmo churches, standing side by side, form one of the most precious religious ensembles in the historic center.",
"es": "Vecina de la antigua catedral en la Praça XV, esta iglesia de la cofradía del Carmen esconde un interior barroco de gran riqueza: talla dorada, retablos labrados y una nave decorada con esplendor. Las dos iglesias del Carmo, una junto a la otra, forman uno de los conjuntos religiosos más preciados del centro histórico.",
"pt": "Vizinha da antiga catedral na Praça XV, essa igreja da irmandade do Carmo esconde um interior barroco de grande riqueza: talha dourada, retábulos entalhados e uma nave decorada com fartura. As duas igrejas do Carmo, lado a lado, formam um dos conjuntos religiosos mais preciosos do centro histórico.",
},
{
"name": "Igreja de N. S. do Carmo (Antiga Sé)",
"fr": "Sur la Praça XV, cette église fut l'ancienne cathédrale de Rio. C'est ici que furent couronnés les empereurs Pierre Ier et Pierre II et que se déroulèrent les grands actes de la famille impériale. Son intérieur rococo, doré et raffiné, tranche avec l'agitation du centre. Un écrin de l'histoire monarchique du Brésil.",
"en": "On Praça XV, this church was once Rio's cathedral. It's here that Emperors Pedro the First and Pedro the Second were crowned, and where the great ceremonies of the imperial family took place. Its gilded, refined rococo interior stands in sharp contrast to the bustle of downtown. A jewel box of Brazil's monarchic history.",
"es": "En la Praça XV, esta iglesia fue la antigua catedral de Río. Aquí fueron coronados los emperadores Pedro Primero y Pedro Segundo, y aquí tuvieron lugar los grandes actos de la familia imperial. Su interior rococó, dorado y refinado, contrasta con el bullicio del centro. Un cofre de la historia monárquica de Brasil.",
"pt": "Na Praça XV, essa igreja foi a antiga catedral do Rio. Foi aqui que os imperadores Pedro Primeiro e Pedro Segundo foram coroados, e onde aconteceram os grandes atos da família imperial. Seu interior rococó, dourado e refinado, contrasta com a agitação do centro. Um estojo precioso da história monárquica do Brasil.",
},
{
"name": "Igreja de São Francisco da Penitência",
"fr": "Derrière une façade sobre, au Largo da Carioca, se cache un trésor : la nef entière est recouverte d'or. Joyau du baroque brésilien achevé au XVIIIe siècle, l'église doit sa gloire au plafond peint par Caetano da Costa Coelho — la première peinture en trompe-l'œil du pays. Prenez un instant pour lever la tête.",
"en": "Behind a plain façade on Largo da Carioca hides a treasure: the entire nave covered in gold. A jewel of Brazilian baroque completed in the eighteenth century, the church owes its fame to the ceiling painted by Caetano da Costa Coelho, the country's first trompe-l'oeil painting. Take a moment to look up.",
"es": "Detrás de una fachada sobria, en el Largo da Carioca, se esconde un tesoro: toda la nave está cubierta de oro. Joya del barroco brasileño terminada en el siglo dieciocho, la iglesia debe su fama al techo pintado por Caetano da Costa Coelho, la primera pintura en trampantojo del país. Tómese un momento para mirar hacia arriba.",
"pt": "Atrás de uma fachada sóbria, no Largo da Carioca, se esconde um tesouro: a nave inteira é coberta de ouro. Joia do barroco brasileiro concluída no século dezoito, a igreja deve sua fama ao teto pintado por Caetano da Costa Coelho, a primeira pintura em trompe-l'oeil do país. Reserve um instante para olhar para cima.",
},
{
"name": "Igreja de São Francisco de Paula",
"fr": "Sur le largo du même nom, cette grande église coloniale recèle des trésors d'art sacré : sculptures de Mestre Valentim et peintures de Manuel da Cunha. Un intérieur richement ouvragé, souvent ignoré des passants pressés.",
"en": "On the square that bears its name, this large colonial church holds treasures of sacred art: sculptures by Mestre Valentim and paintings by Manuel da Cunha. A richly worked interior, often overlooked by hurried passersby.",
"es": "En el largo que lleva su nombre, esta gran iglesia colonial guarda tesoros de arte sacro: esculturas de Mestre Valentim y pinturas de Manuel da Cunha. Un interior ricamente labrado, a menudo ignorado por los transeúntes apresurados.",
"pt": "No largo que leva seu nome, essa grande igreja colonial guarda tesouros de arte sacra: esculturas de Mestre Valentim e pinturas de Manuel da Cunha. Um interior ricamente trabalhado, muitas vezes ignorado pelos passantes apressados.",
},
{
"name": "Lagoa Rodrigo de Freitas",
"fr": "Cette lagune ouverte sur l'océan est l'une des principales attractions touristiques de la ville, surnommée le cœur de Rio de Janeiro. On en fait le tour à pied, à vélo ou en pédalo. Un poumon de calme entre Ipanema et le Jardin botanique.",
"en": "This lagoon, open to the ocean, is one of the city's main tourist attractions, nicknamed the heart of Rio de Janeiro. You can go around it on foot, by bike, or in a paddle boat. A pocket of calm between Ipanema and the Botanical Garden.",
"es": "Esta laguna abierta al océano es una de las principales atracciones turísticas de la ciudad, apodada el corazón de Río de Janeiro. Se puede rodear a pie, en bicicleta o en bote de pedales. Un pulmón de calma entre Ipanema y el Jardín Botánico.",
"pt": "Essa lagoa aberta para o oceano é uma das principais atrações turísticas da cidade, apelidada de coração do Rio de Janeiro. Dá pra dar a volta a pé, de bicicleta ou de pedalinho. Um pulmão de calma entre Ipanema e o Jardim Botânico.",
},
{
"name": "Morro Dois Irmãos",
"fr": "Ces deux pics jumeaux qui ferment la plage d'Ipanema sont l'un des symboles de Rio. Un sentier, accessible depuis le Vidigal, mène en une heure à un sommet d'où la ville, la lagune et l'océan se déploient à 360°. L'une des plus belles récompenses de marche de la ville.",
"en": "These twin peaks closing off Ipanema beach are one of Rio's great symbols. A trail, accessible from Vidigal, leads in about an hour to a summit where the city, the lagoon, and the ocean unfold in a full three-sixty view. One of the best hiking rewards in the city.",
"es": "Estos dos picos gemelos que cierran la playa de Ipanema son uno de los símbolos de Río. Un sendero, accesible desde Vidigal, lleva en una hora a una cima desde donde la ciudad, la laguna y el océano se despliegan en un panorama de trescientos sesenta grados. Una de las mejores recompensas de caminata de la ciudad.",
"pt": "Esses dois picos gêmeos que fecham a praia de Ipanema são um dos símbolos do Rio. Uma trilha, acessível pelo Vidigal, leva em cerca de uma hora a um topo de onde a cidade, a lagoa e o oceano se abrem em trezentos e sessenta graus. Uma das melhores recompensas de trilha da cidade.",
},
{
"name": "Mosteiro de São Bento",
"fr": "Derrière une façade austère se cache l'un des plus somptueux intérieurs baroques du Brésil : un bois entièrement sculpté qui recouvre la nef, façonné entre le XVIIe et le XVIIIe siècle par un moine bénédictin et plusieurs grands maîtres sculpteurs séculiers. Un lieu suspendu, hors du temps, au cœur de la ville.",
"en": "Behind an austere façade hides one of Brazil's most sumptuous baroque interiors: carved wood entirely covering the nave, shaped between the seventeenth and eighteenth centuries by a Benedictine monk and several leading secular master sculptors. A suspended, timeless place in the heart of the city.",
"es": "Detrás de una fachada austera se esconde uno de los interiores barrocos más suntuosos de Brasil: madera enteramente tallada que recubre la nave, moldeada entre los siglos diecisiete y dieciocho por un monje benedictino y varios grandes maestros escultores seculares. Un lugar suspendido, fuera del tiempo, en el corazón de la ciudad.",
"pt": "Atrás de uma fachada austera se esconde um dos interiores barrocos mais suntuosos do Brasil: madeira inteiramente entalhada que recobre a nave, moldada entre os séculos dezessete e dezoito por um monge beneditino e vários grandes mestres escultores seculares. Um lugar suspenso, fora do tempo, no coração da cidade.",
},
{
"name": "Palácio Tiradentes",
"fr": "Ce palais monumental fut le siège de la Chambre des députés du Brésil, puis de l'Assemblée législative de l'État de Rio jusqu'en 2021. L'assemblée doit déménager à Cidade Nova, et le palais est appelé à devenir le Musée de la Démocratie.",
"en": "This monumental palace once housed Brazil's Chamber of Deputies, then Rio's State Assembly until 2021. The assembly is set to move to Cidade Nova, and the palace is expected to become the Museu da Democracia.",
"es": "Este palacio monumental fue sede de la Cámara de Diputados de Brasil, y luego de la Asamblea Legislativa del Estado de Río hasta 2021. La asamblea se trasladará a Cidade Nova, y el palacio está destinado a convertirse en el Museo de la Democracia.",
"pt": "Esse palácio monumental foi sede da Câmara dos Deputados do Brasil, e depois da Assembleia Legislativa do Rio até 2021. A assembleia deve se mudar para a Cidade Nova, e o palácio está destinado a se tornar o Museu da Democracia.",
},
{
"name": "Palácio do Itamaraty",
"fr": "Ce palais du XIXe siècle fut le siège du ministère des Affaires étrangères du Brésil de 1897 à 1970. Il conserve aujourd'hui un musée et de riches archives diplomatiques. Une parenthèse feutrée dans le centre affairé.",
"en": "This nineteenth-century palace was home to Brazil's Ministry of Foreign Affairs from eighteen ninety-seven to nineteen seventy. It now holds a museum and rich diplomatic archives. A hushed pause in the busy downtown.",
"es": "Este palacio del siglo diecinueve fue sede del ministerio de Relaciones Exteriores de Brasil de mil ochocientos noventa y siete a mil novecientos setenta. Hoy conserva un museo y un rico archivo diplomático. Un paréntesis silencioso en el centro ajetreado.",
"pt": "Esse palacete do século dezenove foi sede do Ministério das Relações Exteriores do Brasil de mil oitocentos e noventa e sete a mil novecentos e setenta. Hoje guarda um museu e um rico acervo diplomático. Uma pausa silenciosa no centro agitado.",
},
{
"name": "Parque Lage",
"fr": "Au pied de la forêt de Tijuca, ce parc entoure un palais italianisant des années 1920, avec sa cour intérieure et sa piscine où se reflète le Christ Rédempteur. Ancien domaine devenu école d'arts visuels, c'est un lieu aimé des cariocas pour flâner, prendre un café dans le patio, ou entamer à pied la montée vers le Corcovado.",
"en": "At the foot of the Tijuca forest, this park surrounds an Italian-style mansion from the nineteen twenties, with its inner courtyard and pool reflecting Christ the Redeemer. A former estate turned visual arts school, it's a place cariocas love for strolling, having coffee in the patio, or starting the hike up to Corcovado.",
"es": "Al pie del bosque de Tijuca, este parque rodea un palacete de estilo italiano de los años mil novecientos veinte, con su patio interior y su piscina donde se refleja el Cristo Redentor. Antigua propiedad convertida en escuela de artes visuales, es un lugar querido por los cariocas para pasear, tomar un café en el patio o iniciar a pie la subida al Corcovado.",
"pt": "Ao pé da floresta da Tijuca, esse parque rodeia um palacete de estilo italiano dos anos mil novecentos e vinte, com seu pátio interno e sua piscina onde se reflete o Cristo Redentor. Antigo domínio que virou escola de artes visuais, é um lugar querido pelos cariocas para passear, tomar um café no pátio, ou começar a pé a subida para o Corcovado.",
},
{
"name": "Parque do Flamengo (Aterro)",
"fr": "Gagné sur la mer et paysagé par Roberto Burle Marx dans les années 1960, ce vaste parc en bord de baie relie le centre à Botafogo. Pelouses, pistes cyclables, terrains de sport et vue permanente sur le Pain de Sucre : l'immense terrain de jeu en plein air des cariocas, surtout le dimanche.",
"en": "Reclaimed from the sea and landscaped by Roberto Burle Marx in the nineteen sixties, this vast park along the bay links downtown to Botafogo. Lawns, bike paths, sports fields, and a constant view of Sugarloaf Mountain: the huge open-air playground of the cariocas, especially on Sundays.",
"es": "Ganado al mar y ajardinado por Roberto Burle Marx en los años mil novecientos sesenta, este vasto parque a orillas de la bahía conecta el centro con Botafogo. Céspedes, ciclovías, canchas deportivas y una vista constante del Pan de Azúcar: el enorme patio de recreo al aire libre de los cariocas, sobre todo los domingos.",
"pt": "Ganho do mar e paisagismo de Roberto Burle Marx nos anos mil novecentos e sessenta, esse vasto parque à beira da baía liga o centro a Botafogo. Gramados, ciclovias, quadras esportivas e vista permanente para o Pão de Açúcar: o imenso playground a céu aberto dos cariocas, principalmente aos domingos.",
},
{
"name": "Passeio Público",
"fr": "C'est le plus ancien jardin public du Brésil, dessiné en 1783 par le sculpteur Mestre Valentim. Allées ombragées, fontaines, statues et un petit lac : un havre de fraîcheur qui a vu se promener des générations de cariocas, entre Cinelândia et la Lapa. Un discret morceau d'histoire végétale.",
"en": "This is Brazil's oldest public garden, designed in seventeen eighty-three by the sculptor Mestre Valentim. Shaded pathways, fountains, statues, and a small lake: a cool haven that generations of cariocas have strolled through, between Cinelândia and Lapa. A quiet piece of living history.",
"es": "Este es el jardín público más antiguo de Brasil, diseñado en mil setecientos ochenta y tres por el escultor Mestre Valentim. Alamedas sombreadas, fuentes, estatuas y un pequeño lago: un refugio fresco por donde han paseado generaciones de cariocas, entre la Cinelândia y la Lapa. Un discreto pedazo de historia viva.",
"pt": "Esse é o jardim público mais antigo do Brasil, projetado em mil setecentos e oitenta e três pelo escultor Mestre Valentim. Alamedas sombreadas, fontes, estátuas e um lago pequeno: um refúgio fresco por onde passearam gerações de cariocas, entre a Cinelândia e a Lapa. Um pedacinho discreto de história viva.",
},
{
"name": "Sambódromo da Marquês de Sapucaí",
"fr": "Inauguré en 1984, ce long couloir bordé de gradins est le théâtre du carnaval le plus célèbre du Brésil : chaque nuit de Carnaval, les écoles de samba y défilent devant des dizaines de milliers de spectateurs. Le reste de l'année, on peut le visiter, étrangement calme et immense.",
"en": "Opened in nineteen eighty-four, this long corridor lined with grandstands is the stage for Brazil's most famous carnival: every Carnival night, samba schools parade here in front of tens of thousands of spectators. The rest of the year, you can visit it, strangely calm and vast.",
"es": "Inaugurado en mil novecientos ochenta y cuatro, este largo pasillo bordeado de gradas es el escenario del carnaval más famoso de Brasil: cada noche de Carnaval, las escuelas de samba desfilan aquí ante decenas de miles de espectadores. El resto del año, se puede visitar, extrañamente tranquilo e inmenso.",
"pt": "Inaugurado em mil novecentos e oitenta e quatro, esse longo corredor ladeado de arquibancadas é o palco do carnaval mais famoso do Brasil: toda noite de Carnaval, as escolas de samba desfilam ali diante de dezenas de milhares de espectadores. No resto do ano, dá pra visitar, estranhamente calmo e imenso.",
},
{
"name": "Espaço Cultural Trem do Corcovado",
"fr": "Depuis 1884, ce petit train à crémaillère grimpe à travers la forêt de Tijuca jusqu'aux pieds du Christ Rédempteur. Vingt minutes de montée dans une végétation dense, avec des échappées sur la ville. Plus qu'un trajet : une traversée de la plus grande forêt urbaine du monde.",
"en": "Since eighteen eighty-four, this little cog railway has climbed through the Tijuca forest right up to the feet of Christ the Redeemer. Twenty minutes of climbing through dense vegetation, with glimpses of the city along the way. More than a ride, it's a crossing of the largest urban forest in the world.",
"es": "Desde mil ochocientos ochenta y cuatro, este pequeño tren de cremallera sube a través del bosque de Tijuca hasta los pies del Cristo Redentor. Veinte minutos de ascenso entre vegetación densa, con vistas de la ciudad. Más que un trayecto: un recorrido por el bosque urbano más grande del mundo.",
"pt": "Desde mil oitocentos e oitenta e quatro, esse trenzinho de cremalheira sobe pela floresta da Tijuca até os pés do Cristo Redentor. Vinte minutos de subida em meio a uma vegetação densa, com vistas da cidade pelo caminho. Mais que um trajeto: uma travessia pela maior floresta urbana do mundo.",
},
{
"name": "Museu Histórico Nacional",
"fr": "Installé dans un ancien arsenal au bord de la baie, ce musée retrace cinq siècles d'histoire brésilienne : carrosses impériaux, armes, monnaies, objets du quotidien colonial. L'une des plus riches collections du pays. Un passage obligé pour comprendre le fil qui relie l'indépendance, l'Empire et la République.",
"en": "Housed in a former arsenal by the bay, this museum traces five centuries of Brazilian history: imperial carriages, weapons, coins, everyday colonial objects. One of the richest collections in the country. A must to understand the thread linking independence, the Empire, and the Republic.",
"es": "Instalado en un antiguo arsenal a orillas de la bahía, este museo recorre cinco siglos de historia brasileña: carruajes imperiales, armas, monedas, objetos cotidianos coloniales. Una de las colecciones más ricas del país. Una parada obligatoria para entender el hilo que une la independencia, el Imperio y la República.",
"pt": "Instalado em um antigo arsenal à beira da baía, esse museu percorre cinco séculos de história brasileira: carruagens imperiais, armas, moedas, objetos do cotidiano colonial. Uma das coleções mais ricas do país. Uma parada obrigatória para entender o fio que liga a independência, o Império e a República.",
},
{
"name": "Museu Histórico da Cidade RJ",
"fr": "Niché dans le Parque da Cidade, à la Gávea, ce musée retrace l'histoire de Rio dans une ancienne demeure entourée de jardins. Gravures, mobilier et objets racontent la ville coloniale et impériale. Un lieu calme et verdoyant, à l'écart de l'agitation, pour prendre du recul sur toute la cité.",
"en": "Tucked away in Parque da Cidade, in Gávea, this museum tells the story of Rio inside a former mansion surrounded by gardens. Engravings, furniture, and objects tell the story of colonial and imperial Rio. A calm, green place, away from the bustle, to step back and look at the whole city.",
"es": "Escondido en el Parque da Cidade, en Gávea, este museo cuenta la historia de Río en una antigua residencia rodeada de jardines. Grabados, mobiliario y objetos narran la ciudad colonial e imperial. Un lugar tranquilo y verde, alejado del bullicio, para tomar perspectiva sobre toda la ciudad.",
"pt": "Escondido no Parque da Cidade, na Gávea, esse museu conta a história do Rio dentro de uma antiga residência cercada de jardins. Gravuras, mobiliário e objetos narram a cidade colonial e imperial. Um lugar calmo e verde, longe da agitação, para dar um passo atrás e olhar pra cidade inteira.",
},
{
"name": "Museu da República (Palácio do Catete)",
"fr": "Ce palais du XIXe siècle fut la résidence des présidents brésiliens pendant des décennies. Getúlio Vargas s'y donna la mort en 1954 ; le revolver et le pyjama qu'il portait cette nuit-là sont conservés dans la collection du musée. Devenu Musée de la République, il s'entoure d'un jardin public paisible, refuge apprécié au cœur du Catete.",
"en": "This nineteenth-century palace was home to Brazilian presidents for decades. Getúlio Vargas took his own life here in nineteen fifty-four; the revolver and pajamas he wore that night are kept in the museum's collection. Now the Museum of the Republic, it's surrounded by a peaceful public garden, a beloved retreat in the heart of Catete.",
"es": "Este palacio del siglo diecinueve fue la residencia de los presidentes brasileños durante décadas. Getúlio Vargas se quitó la vida aquí en mil novecientos cincuenta y cuatro; el revólver y el pijama que llevaba esa noche se conservan en la colección del museo. Convertido en Museo de la República, está rodeado de un tranquilo jardín público, un refugio apreciado en el corazón de Catete.",
"pt": "Esse palacete do século dezenove foi a residência dos presidentes brasileiros por décadas. Getúlio Vargas tirou a própria vida aqui em mil novecentos e cinquenta e quatro; o revólver e o pijama que usava naquela noite são guardados na coleção do museu. Transformado em Museu da República, ele é cercado por um jardim público tranquilo, um refúgio querido no coração do Catete.",
},
{
"name": "Arcos Da Lapa - Vida Boemia Do Rio De Janeiro",
"fr": "Ces quarante-deux arches blanches sont les vestiges de l'aqueduc de la Carioca, bâti au XVIIIe siècle pour amener l'eau de la forêt jusqu'au centre. Long de près de 270 mètres, il ne porte plus d'eau depuis longtemps : c'est le petit tramway jaune de Santa Teresa qui passe à son sommet. En contrebas, la Lapa et ses nuits de samba.",
"en": "These forty-two white arches are what remains of the Carioca aqueduct, built in the eighteenth century to carry water from the forest into downtown. Nearly two hundred seventy meters long, it hasn't carried water in a long time, now it's the little yellow tram of Santa Teresa that crosses on top. Below, Lapa and its nights of samba.",
"es": "Estos cuarenta y dos arcos blancos son los vestigios del acueducto de la Carioca, construido en el siglo dieciocho para llevar agua del bosque hasta el centro. Con casi doscientos setenta metros de largo, hace mucho que no lleva agua, ahora es el pequeño tranvía amarillo de Santa Teresa el que pasa por encima. Más abajo, la Lapa y sus noches de samba.",
"pt": "Esses quarenta e dois arcos brancos são os vestígios do aqueduto da Carioca, construído no século dezoito para levar água da floresta até o centro. Com quase duzentos e setenta metros de comprimento, faz tempo que não carrega água, agora é o bondinho amarelo de Santa Teresa que passa por cima. Lá embaixo, a Lapa e suas noites de samba.",
},
{
"name": "Boulevard Olímpico — Mural Etnias",
"fr": "Le long du port réhabilité s'étire le Boulevard Olympique et ses fresques géantes. La plus célèbre, « Etnias » de l'artiste Eduardo Kobra, représente cinq visages des cinq continents et fut un temps la plus grande murale du monde. Street art, food trucks et vue sur la baie : le nouveau rendez-vous carioca.",
"en": "Along the redeveloped port stretches the Boulevard Olímpico with its giant murals. The most famous, 'Etnias' by artist Eduardo Kobra, depicts five faces from the five continents and was once the largest mural in the world. Street art, food trucks, and a view over the bay: Rio's new gathering spot.",
"es": "A lo largo del puerto renovado se extiende el Boulevard Olímpico y sus murales gigantes. El más famoso, 'Etnias' del artista Eduardo Kobra, representa cinco rostros de los cinco continentes y fue en su momento el mural más grande del mundo. Arte urbano, food trucks y vista sobre la bahía: el nuevo punto de encuentro carioca.",
"pt": "Ao longo do porto revitalizado se estende o Boulevard Olímpico e seus murais gigantes. O mais famoso, 'Etnias', do artista Eduardo Kobra, representa cinco rostos dos cinco continentes e já foi o maior mural do mundo. Arte de rua, food trucks e vista para a baía: o novo point carioca.",
},
{
"name": "Cascatinha Taunay",
"fr": "Au cœur de la forêt de Tijuca, cette cascade fut immortalisée par le peintre français Nicolas-Antoine Taunay au début du XIXe siècle. Facile d'accès, entourée d'une végétation luxuriante, elle rappelle que Rio abrite la plus grande forêt urbaine du monde — replantée à la main après le déboisement des plantations de café.",
"en": "In the heart of the Tijuca forest, this waterfall was immortalized by French painter Nicolas-Antoine Taunay in the early nineteenth century. Easy to reach and surrounded by lush vegetation, it's a reminder that Rio is home to the largest urban forest in the world, replanted by hand after the coffee plantations had stripped it bare.",
"es": "En el corazón del bosque de Tijuca, esta cascada fue inmortalizada por el pintor francés Nicolas-Antoine Taunay a principios del siglo diecinueve. Fácil de acceder, rodeada de vegetación exuberante, recuerda que Río alberga el bosque urbano más grande del mundo, replantado a mano tras la deforestación de las plantaciones de café.",
"pt": "No coração da floresta da Tijuca, essa cachoeira foi eternizada pelo pintor francês Nicolas-Antoine Taunay no início do século dezenove. De fácil acesso, cercada de vegetação exuberante, ela lembra que o Rio abriga a maior floresta urbana do mundo, replantada à mão depois do desmatamento das plantações de café.",
},
{
"name": "Comunidade do Vidigal",
"fr": "Accrochée à la colline entre Leblon et São Conrado, cette favela offre l'une des plus belles vues de Rio sur la mer. Devenue un pôle d'art, de bars et d'auberges, elle est aussi le point de départ de la randonnée vers le Morro Dois Irmãos. À découvrir avec respect, idéalement accompagné d'un guide local.",
"en": "Clinging to the hillside between Leblon and São Conrado, this favela offers one of Rio's best ocean views. Now a hub of art, bars, and hostels, it's also the starting point for the hike up to Morro Dois Irmãos. Best explored respectfully, ideally with a local guide.",
"es": "Aferrada a la colina entre Leblon y São Conrado, esta favela ofrece una de las mejores vistas al mar de Río. Convertida en un polo de arte, bares y albergues, es también el punto de partida de la caminata hacia el Morro Dois Irmãos. Para descubrir con respeto, idealmente acompañado de un guía local.",
"pt": "Grudada na encosta entre Leblon e São Conrado, essa favela oferece uma das vistas mais bonitas do Rio para o mar. Virou um polo de arte, bares e albergues, e é também o ponto de partida da trilha para o Morro Dois Irmãos. Para descobrir com respeito, idealmente acompanhado de um guia local.",
},
{
"name": "Confeitaria Colombo",
"fr": "Poussez la porte et vous voilà dans la Belle Époque carioca. Fondée en 1894 par des immigrants portugais, la Confeitaria Colombo a gardé ses grands miroirs, ses vitraux et ses boiseries sous une verrière Art nouveau. On y prend le thé comme il y a un siècle. L'un des plus beaux cafés du monde, et un morceau vivant de l'histoire de Rio.",
"en": "Push open the door and you step into carioca's Belle Époque. Founded in eighteen ninety-four by Portuguese immigrants, the Confeitaria Colombo has kept its great mirrors, stained glass, and woodwork under an Art Nouveau glass roof. You can still have tea here just as they did a century ago. One of the most beautiful cafés in the world, and a living piece of Rio's history.",
"es": "Empuje la puerta y estará en la Belle Époque carioca. Fundada en mil ochocientos noventa y cuatro por inmigrantes portugueses, la Confeitaria Colombo ha conservado sus grandes espejos, sus vitrales y su carpintería bajo un techo de vidrio Art Nouveau. Se toma el té aquí como hace un siglo. Uno de los cafés más bellos del mundo, y un pedazo vivo de la historia de Río.",
"pt": "Empurre a porta e você entra na Belle Époque carioca. Fundada em mil oitocentos e noventa e quatro por imigrantes portugueses, a Confeitaria Colombo manteve seus grandes espelhos, vitrais e madeiras entalhadas sob uma claraboia Art Nouveau. Toma-se chá ali como há um século. Um dos cafés mais bonitos do mundo, e um pedaço vivo da história do Rio.",
},
{
"name": "Favela da Rocinha",
"fr": "Accrochée à flanc de colline au-dessus de São Conrado, la Rocinha est la plus grande favela du Brésil : une ville dans la ville, dense, débrouillarde et pleine de vie. Des visites guidées menées par des habitants permettent de la découvrir avec respect, loin des clichés, au plus près du quotidien carioca.",
"en": "Clinging to the hillside above São Conrado, Rocinha is the largest favela in Brazil: a city within a city, dense, resourceful, and full of life. Guided tours led by residents let you discover it respectfully, far from clichés, close to everyday carioca life.",
"es": "Aferrada a la ladera sobre São Conrado, la Rocinha es la favela más grande de Brasil: una ciudad dentro de la ciudad, densa, ingeniosa y llena de vida. Visitas guiadas dirigidas por sus propios habitantes permiten descubrirla con respeto, lejos de los clichés, muy cerca del día a día carioca.",
"pt": "Grudada na encosta acima de São Conrado, a Rocinha é a maior favela do Brasil: uma cidade dentro da cidade, densa, cheia de jeitinho e de vida. Visitas guiadas conduzidas por moradores permitem conhecê-la com respeito, longe dos clichês, bem perto do dia a dia carioca.",
},
{
"name": "Lar",
"fr": "Ces marches couvertes de mosaïques éclatantes sont l'œuvre d'un seul homme : l'artiste chilien Jorge Selarón. À partir de 1990, il a recouvert cet escalier entre Lapa et Santa Teresa de plus de deux mille carreaux venus du monde entier. Il y a travaillé jusqu'à sa mort, en 2013. Une déclaration d'amour au Brésil, à ciel ouvert.",
"en": "These steps covered in dazzling mosaics are the work of a single man: Chilean artist Jorge Selarón. Starting in nineteen ninety, he covered this staircase between Lapa and Santa Teresa with more than two thousand tiles from all over the world. He kept working on it until his death in twenty thirteen. An open-air declaration of love for Brazil.",
"es": "Estos escalones cubiertos de mosaicos deslumbrantes son obra de un solo hombre: el artista chileno Jorge Selarón. A partir de mil novecientos noventa, cubrió esta escalera entre la Lapa y Santa Teresa con más de dos mil azulejos venidos de todo el mundo. Trabajó en ella hasta su muerte, en dos mil trece. Una declaración de amor a Brasil, a cielo abierto.",
"pt": "Essa escadaria coberta de mosaicos deslumbrantes é obra de um único homem: o artista chileno Jorge Selarón. A partir de mil novecentos e noventa, ele cobriu essa escadaria entre a Lapa e Santa Teresa com mais de dois mil azulejos vindos do mundo inteiro. Trabalhou nela até sua morte, em dois mil e treze. Uma declaração de amor ao Brasil, a céu aberto.",
},
]
