# -*- coding: utf-8 -*-
# Adaptations multilingues (EN/ES/PT-BR) — partie 3/4

DATA_PART3 = [
{
"name": "Mirante Dona Marta",
"fr": "Ce belvédère, accessible par la route à travers la forêt, offre l'une des vues les plus complètes sur Rio : le Pain de Sucre, la baie, Botafogo, et le Christ juste au-dessus. C'est d'ici que sont prises beaucoup des cartes postales de la ville. Idéal en fin d'après-midi.",
"en": "This lookout, reached by a road through the forest, offers one of the most complete views over Rio: Sugarloaf Mountain, the bay, Botafogo, and Christ the Redeemer right above. Many of the city's postcard shots are taken from here. Ideal in the late afternoon.",
"es": "Este mirador, al que se llega por una carretera a través del bosque, ofrece una de las vistas más completas de Río: el Pan de Azúcar, la bahía, Botafogo, y el Cristo justo encima. Desde aquí se toman muchas de las postales de la ciudad. Ideal a última hora de la tarde.",
"pt": "Esse mirante, acessado por uma estrada que atravessa a floresta, oferece uma das vistas mais completas do Rio: o Pão de Açúcar, a baía, Botafogo, e o Cristo bem acima. É daqui que saem muitos dos cartões-postais da cidade. Ideal no fim da tarde.",
},
{
"name": "Mirante da Praia Vermelha",
"fr": "Petite crique de sable doré nichée au pied du Pain de Sucre, protégée des vagues et cernée de végétation. C'est aussi le départ de la Pista Cláudio Coutinho, un sentier plat au bord de l'eau. Un coin de calme à deux pas de l'agitation d'Urca, avec une vue superbe sur les mornes.",
"en": "A small golden-sand cove nestled at the foot of Sugarloaf Mountain, sheltered from the waves and surrounded by greenery. It's also the starting point of the Pista Cláudio Coutinho, a flat trail along the water. A calm spot just steps from the bustle of Urca, with a superb view of the hills.",
"es": "Una pequeña cala de arena dorada anidada al pie del Pan de Azúcar, protegida de las olas y rodeada de vegetación. Es también el punto de partida de la Pista Cláudio Coutinho, un sendero llano junto al agua. Un rincón de calma a pocos pasos del bullicio de Urca, con una vista magnífica de los cerros.",
"pt": "Uma pequena enseada de areia dourada aninhada aos pés do Pão de Açúcar, protegida das ondas e cercada de vegetação. É também o ponto de partida da Pista Cláudio Coutinho, uma trilha plana à beira d'água. Um canto de calma a poucos passos da agitação de Urca, com uma vista soberba dos morros.",
},
{
"name": "Mirante do Pão de Açúcar",
"fr": "Ce piton de granit de 396 mètres qui plonge dans la mer, c'est le Pain de Sucre. Depuis 1912, un téléphérique — le fameux bondinho — vous hisse en deux tronçons, d'abord au morro da Urca puis au sommet. Là-haut, la vue embrasse la baie de Guanabara, Copacabana et, au loin, le Christ. Venez au coucher du soleil.",
"en": "This three-hundred-ninety-six-meter granite peak plunging into the sea is Sugarloaf Mountain. Since nineteen twelve, a cable car, the famous bondinho, lifts you up in two stages, first to Morro da Urca, then to the summit. Up there, the view spans Guanabara Bay, Copacabana, and, in the distance, Christ the Redeemer. Come at sunset.",
"es": "Este pico de granito de trescientos noventa y seis metros que se hunde en el mar es el Pan de Azúcar. Desde mil novecientos doce, un teleférico, el famoso bondinho, lo sube en dos tramos, primero al Morro da Urca y luego a la cima. Allá arriba, la vista abarca la bahía de Guanabara, Copacabana y, a lo lejos, el Cristo. Venga al atardecer.",
"pt": "Esse pico de granito de trezentos e noventa e seis metros que mergulha no mar é o Pão de Açúcar. Desde mil novecentos e doze, um bondinho leva você em dois trechos, primeiro ao Morro da Urca, depois ao topo. Lá em cima, a vista abraça a baía de Guanabara, Copacabana e, ao longe, o Cristo. Venha no pôr do sol.",
},
{
"name": "Morro da Urca",
"fr": "Premier arrêt du téléphérique du Pain de Sucre, ce morne de 220 mètres offre déjà une vue splendide sur Botafogo, le Christ et la baie. On peut aussi y monter à pied par un sentier depuis la Praia Vermelha. En haut, restaurants et scène de concerts en plein air certains soirs.",
"en": "The first stop of the Sugarloaf cable car, this two-hundred-twenty-meter hill already offers a splendid view over Botafogo, Christ the Redeemer, and the bay. You can also hike up on a trail from Praia Vermelha. At the top, restaurants and, some evenings, an open-air concert stage.",
"es": "Primera parada del teleférico del Pan de Azúcar, este cerro de doscientos veinte metros ya ofrece una vista espléndida sobre Botafogo, el Cristo y la bahía. También se puede subir a pie por un sendero desde la Praia Vermelha. Arriba, restaurantes y, algunas noches, un escenario de conciertos al aire libre.",
"pt": "Primeira parada do bondinho do Pão de Açúcar, esse morro de duzentos e vinte metros já oferece uma vista esplêndida de Botafogo, do Cristo e da baía. Também dá pra subir a pé por uma trilha a partir da Praia Vermelha. Lá em cima, restaurantes e, em algumas noites, um palco de shows ao ar livre.",
},
{
"name": "Museu de Arte Contemporânea de Niterói (MAC)",
"fr": "De l'autre côté de la baie, cette soucoupe blanche posée sur la falaise est l'œuvre d'Oscar Niemeyer, inaugurée en 1996. Le Musée d'art contemporain de Niterói vaut autant pour ses expositions que pour sa silhouette et sa vue à 360° sur Rio. La traversée en ferry depuis la Praça XV fait partie du plaisir.",
"en": "On the other side of the bay, this white flying-saucer shape perched on the cliff is the work of Oscar Niemeyer, opened in nineteen ninety-six. The Niterói Contemporary Art Museum is worth visiting as much for its exhibitions as for its silhouette and its full three-sixty view of Rio. The ferry crossing from Praça XV is part of the fun.",
"es": "Al otro lado de la bahía, esta blanca forma de platillo volador posada sobre el acantilado es obra de Oscar Niemeyer, inaugurada en mil novecientos noventa y seis. El Museo de Arte Contemporáneo de Niterói vale tanto por sus exposiciones como por su silueta y su vista de trescientos sesenta grados sobre Río. La travesía en ferry desde la Praça XV forma parte del placer.",
"pt": "Do outro lado da baía, essa forma branca de disco voador pousada no penhasco é obra de Oscar Niemeyer, inaugurada em mil novecentos e noventa e seis. O Museu de Arte Contemporânea de Niterói vale tanto pelas exposições quanto pela silhueta e pela vista de trezentos e sessenta graus do Rio. A travessia de barca desde a Praça XV já faz parte do passeio.",
},
{
"name": "Palacio da Ilha Fiscal",
"fr": "Ce petit château néo-gothique vert d'eau, posé sur un îlot de la baie, servait au contrôle des douanes. Il doit sa célébrité à une seule nuit : le dernier grand bal de l'Empire, en novembre 1889, quelques jours avant la chute de la monarchie. On y accède en bateau depuis le Musée naval — une visite romanesque.",
"en": "This small seafoam-green neo-gothic castle, perched on an islet in the bay, once served for customs control. It owes its fame to a single night: the last great ball of the Empire, in November eighteen eighty-nine, just days before the monarchy fell. You reach it by boat from the Naval Museum, a romantic outing.",
"es": "Este pequeño castillo neogótico de color verde agua, sobre un islote de la bahía, servía para el control aduanero. Debe su fama a una sola noche: el último gran baile del Imperio, en noviembre de mil ochocientos ochenta y nueve, pocos días antes de la caída de la monarquía. Se llega en barco desde el Museo Naval, una visita romántica.",
"pt": "Esse pequeno castelo neogótico verde-água, sobre uma ilhota da baía, servia para o controle alfandegário. Deve sua fama a uma única noite: o último grande baile do Império, em novembro de mil oitocentos e oitenta e nove, poucos dias antes da queda da monarquia. Chega-se de barco a partir do Museu Naval, um passeio romântico.",
},
{
"name": "Pedra da Gávea - Rio de Janeiro",
"fr": "Ce colossal monolithe de plus de 800 mètres, l'un des plus hauts sommets côtiers du monde, domine São Conrado. Sa randonnée exigeante, avec un passage d'escalade, récompense les plus sportifs d'une vue vertigineuse sur toute la ville et l'océan. À faire accompagné et par temps clair.",
"en": "This colossal monolith, over eight hundred meters tall, one of the highest coastal peaks in the world, towers over São Conrado. Its demanding hike, which includes a climbing section, rewards the fittest with a dizzying view over the whole city and the ocean. Best done with a guide, on a clear day.",
"es": "Este colosal monolito de más de ochocientos metros, uno de los picos costeros más altos del mundo, domina São Conrado. Su exigente caminata, con un tramo de escalada, recompensa a los más deportistas con una vista vertiginosa sobre toda la ciudad y el océano. Mejor hacerlo acompañado y en un día despejado.",
"pt": "Esse colossal monólito com mais de oitocentos metros, um dos picos costeiros mais altos do mundo, domina São Conrado. Sua trilha exigente, com um trecho de escalada, recompensa os mais esportistas com uma vista de tirar o fôlego sobre a cidade toda e o oceano. Melhor fazer acompanhado e em dia de tempo aberto.",
},
{
"name": "Praça Vista Chinesa",
"fr": "Ce belvédère en forme de pavillon oriental, perché dans la forêt de Tijuca à environ 380 mètres, offre l'une des plus belles vues de Rio : la Lagoa, Ipanema, le Pain de Sucre et le Corcovado dans un même cadre. Son pavillon rend hommage aux travailleurs chinois venus cultiver le thé au XIXe siècle. À rejoindre à travers la forêt.",
"en": "This lookout shaped like an oriental pavilion, perched in the Tijuca forest at about three hundred eighty meters, offers one of Rio's finest views: the Lagoa, Ipanema, Sugarloaf Mountain, and the Corcovado all in a single frame. Its pavilion honors the Chinese workers who came to grow tea in the nineteenth century. Reached through the forest.",
"es": "Este mirador con forma de pabellón oriental, encaramado en el bosque de Tijuca a unos trescientos ochenta metros, ofrece una de las vistas más bellas de Río: la Lagoa, Ipanema, el Pan de Azúcar y el Corcovado en un mismo cuadro. Su pabellón rinde homenaje a los trabajadores chinos que vinieron a cultivar té en el siglo diecinueve. Se llega a través del bosque.",
"pt": "Esse mirante em forma de pavilhão oriental, no alto da floresta da Tijuca a cerca de trezentos e oitenta metros, oferece uma das vistas mais bonitas do Rio: a Lagoa, Ipanema, o Pão de Açúcar e o Corcovado em um único quadro. Seu pavilhão homenageia os trabalhadores chineses que vieram cultivar chá no século dezenove. Chega-se atravessando a floresta.",
},
{
"name": "Mam - Museu de Arte Moderna",
"fr": "En bordure du parc du Flamengo, ce chef-d'œuvre du modernisme des années 1950 semble flotter sur ses piliers de béton, entouré de jardins dessinés par Roberto Burle Marx. À l'intérieur, l'une des grandes collections d'art moderne et contemporain du pays, et une cinémathèque réputée. Le modernisme brésilien dans toute sa force.",
"en": "On the edge of Parque do Flamengo, this nineteen-fifties modernist masterpiece seems to float on its concrete pillars, surrounded by gardens designed by Roberto Burle Marx. Inside, one of the country's great collections of modern and contemporary art, plus a renowned film archive. Brazilian modernism in full force.",
"es": "En el borde del parque del Flamengo, esta obra maestra del modernismo de los años mil novecientos cincuenta parece flotar sobre sus pilares de concreto, rodeada de jardines diseñados por Roberto Burle Marx. En su interior, una de las grandes colecciones de arte moderno y contemporáneo del país, y una reconocida cinemateca. El modernismo brasileño en toda su fuerza.",
"pt": "Na borda do Parque do Flamengo, essa obra-prima do modernismo dos anos mil novecentos e cinquenta parece flutuar sobre seus pilares de concreto, cercada de jardins assinados por Roberto Burle Marx. Por dentro, uma das grandes coleções de arte moderna e contemporânea do país, e uma cinemateca renomada. O modernismo brasileiro em toda sua força.",
},
{
"name": "Praça General Osório (Feira Hippie)",
"fr": "Sur cette place ombragée d'Ipanema se tient, chaque dimanche depuis 1968, la célèbre Feira Hippie : artisanat, bijoux, cuir, peintures et cuisine de rue. C'est le rendez-vous dominical des cariocas et des visiteurs en quête de souvenirs faits main. Ambiance bon enfant sous les grands arbres.",
"en": "On this shaded square in Ipanema, every Sunday since nineteen sixty-eight, the famous Feira Hippie takes place: crafts, jewelry, leather goods, paintings, and street food. It's the Sunday gathering spot for cariocas and visitors looking for handmade souvenirs. A friendly atmosphere under the big trees.",
"es": "En esta plaza sombreada de Ipanema se celebra, cada domingo desde mil novecientos sesenta y ocho, la famosa Feira Hippie: artesanía, joyas, cuero, pinturas y comida callejera. Es el punto de encuentro dominical de los cariocas y visitantes en busca de recuerdos hechos a mano. Ambiente familiar bajo los grandes árboles.",
"pt": "Nessa praça sombreada de Ipanema acontece, todo domingo desde mil novecentos e sessenta e oito, a famosa Feira Hippie: artesanato, joias, couro, pinturas e comida de rua. É o point dominical dos cariocas e visitantes em busca de lembrancinhas feitas à mão. Clima gostoso e familiar debaixo das árvores grandes.",
},
{
"name": "AquaRio - Aquário Marinho do Rio",
"fr": "Ouvert en 2016 dans la zone portuaire réhabilitée, l'AquaRio est le plus grand aquarium marin d'Amérique du Sud. Ses vingt-huit bassins réunissent des milliers d'animaux dans quatre millions et demi de litres d'eau. Le clou : un tunnel où raies et requins glissent au-dessus de votre tête. Parfait avec des enfants.",
"en": "Opened in twenty sixteen in the redeveloped port area, AquaRio is the largest marine aquarium in South America. Its twenty-eight tanks bring together thousands of animals in four and a half million liters of water. The highlight: a tunnel where rays and sharks glide right over your head. Perfect with kids.",
"es": "Inaugurado en dos mil dieciséis en la zona portuaria renovada, el AquaRio es el acuario marino más grande de Sudamérica. Sus veintiocho tanques reúnen a miles de animales en cuatro millones y medio de litros de agua. Lo más destacado: un túnel donde rayas y tiburones se deslizan justo sobre su cabeza. Perfecto con niños.",
"pt": "Aberto em dois mil e dezesseis na zona portuária revitalizada, o AquaRio é o maior aquário marinho da América do Sul. Seus vinte e oito tanques reúnem milhares de animais em quatro milhões e meio de litros de água. O destaque: um túnel onde arraias e tubarões deslizam bem acima da sua cabeça. Perfeito com crianças.",
},
{
"name": "Espaço Cultural da Marinha",
"fr": "Au bord de l'eau, cet espace de la Marine brésilienne abrite une part importante de son patrimoine. C'est aussi d'ici que partent chaque jour des bateaux vers l'Ilha Fiscal. Une escale idéale pour les amateurs d'histoire maritime et les familles.",
"en": "By the water, this Brazilian Navy space holds a significant part of its heritage collection. It's also from here that boats depart daily for Ilha Fiscal. An ideal stop for maritime history buffs and families.",
"es": "Junto al agua, este espacio de la Marina brasileña alberga una parte importante de su patrimonio. También es de aquí de donde parten cada día los barcos hacia la Ilha Fiscal. Una parada ideal para los aficionados a la historia marítima y las familias.",
"pt": "À beira d'água, esse espaço da Marinha brasileira abriga parte importante de seu acervo. É também daqui que partem diariamente os barcos para a Ilha Fiscal. Uma parada ideal para os apaixonados por história naval e para famílias.",
},
{
"name": "Museu Nacional",
"fr": "Installé dans l'ancien palais impérial, c'est la plus ancienne institution scientifique du Brésil, fondée en 1818. Un terrible incendie l'a ravagé en 2018, détruisant la majeure partie de ses vingt millions de pièces. Depuis 2025, il rouvre par étapes — on peut y revoir la météorite Bendegó — en attendant la réouverture complète. L'histoire d'une renaissance.",
"en": "Housed in the former imperial palace, this is Brazil's oldest scientific institution, founded in eighteen eighteen. A terrible fire ravaged it in twenty eighteen, destroying most of its twenty million pieces. Since twenty twenty-five, it has been reopening in stages, you can see the Bendegó meteorite again, while awaiting full reopening. The story of a rebirth.",
"es": "Instalado en el antiguo palacio imperial, es la institución científica más antigua de Brasil, fundada en mil ochocientos dieciocho. Un terrible incendio lo devastó en dos mil dieciocho, destruyendo la mayor parte de sus veinte millones de piezas. Desde dos mil veinticinco, va reabriendo por etapas, se puede volver a ver el meteorito Bendegó, mientras se espera la reapertura completa. La historia de un renacimiento.",
"pt": "Instalado no antigo palácio imperial, é a mais antiga instituição científica do Brasil, fundada em mil oitocentos e dezoito. Um incêndio terrível o devastou em dois mil e dezoito, destruindo a maior parte de suas vinte milhões de peças. Desde dois mil e vinte e cinco, ele reabre por etapas, já dá pra rever o meteorito Bendegó, enquanto se aguarda a reabertura completa. A história de um renascimento.",
},
{
"name": "Museu Nacional de Belas Artes",
"fr": "Ce musée conserve la plus importante collection d'art brésilien du XIXe siècle du pays : peintres brésiliens, maîtres européens, et un fonds né de la collection que le roi Jean VI apporta du Portugal. Installé dans l'ancienne École des beaux-arts, c'est le pendant artistique de ce quartier voué à la culture.",
"en": "This museum holds the country's most important collection of nineteenth-century Brazilian art: Brazilian painters, European masters, and a core collection that King João the Sixth brought over from Portugal. Housed in the former School of Fine Arts, it's the artistic counterpart of this culture-devoted quarter.",
"es": "Este museo conserva la colección de arte brasileño del siglo diecinueve más importante del país: pintores brasileños, maestros europeos, y un fondo nacido de la colección que el rey Juan Sexto trajo de Portugal. Instalado en la antigua Escuela de Bellas Artes, es la contraparte artística de este barrio dedicado a la cultura.",
"pt": "Esse museu guarda a coleção de arte brasileira do século dezenove mais importante do país: pintores brasileiros, mestres europeus, e um acervo nascido da coleção que o rei Dom João Sexto trouxe de Portugal. Instalado na antiga Escola de Belas Artes, é o par artístico desse bairro dedicado à cultura.",
},
{
"name": "Museu da Imagem e do Som (MIS)",
"fr": "Le MIS conserve la mémoire sonore et audiovisuelle de Rio : samba, choro, cinéma, radio, télévision. Archives, disques, photographies et expositions racontent la culture populaire brésilienne du XXe siècle. Un incontournable pour qui aime la musique carioca.",
"en": "The MIS preserves Rio's sound and audiovisual memory: samba, choro, film, radio, television. Archives, records, photographs, and exhibitions tell the story of twentieth-century Brazilian popular culture. A must for anyone who loves carioca music.",
"es": "El MIS conserva la memoria sonora y audiovisual de Río: samba, choro, cine, radio, televisión. Archivos, discos, fotografías y exposiciones narran la cultura popular brasileña del siglo veinte. Una parada obligatoria para quien ame la música carioca.",
"pt": "O MIS guarda a memória sonora e audiovisual do Rio: samba, choro, cinema, rádio, televisão. Acervos, discos, fotografias e exposições contam a cultura popular brasileira do século vinte. Uma parada obrigatória para quem ama a música carioca.",
},
{
"name": "Museu de Favela MUF",
"fr": "Sur les hauteurs entre Ipanema et Copacabana, ce musée à ciel ouvert raconte l'histoire de la communauté à travers des fresques peintes sur les façades des maisons. Créé par des habitants, il transforme la favela elle-même en parcours culturel. Une autre manière, digne et vivante, de voir Rio.",
"en": "On the heights between Ipanema and Copacabana, this open-air museum tells the community's story through murals painted on the fronts of houses. Created by residents themselves, it turns the favela into a cultural trail. Another way, dignified and alive, of seeing Rio.",
"es": "En las alturas entre Ipanema y Copacabana, este museo al aire libre cuenta la historia de la comunidad a través de murales pintados en las fachadas de las casas. Creado por los propios habitantes, transforma la favela misma en un recorrido cultural. Otra manera, digna y viva, de ver Río.",
"pt": "No alto entre Ipanema e Copacabana, esse museu a céu aberto conta a história da comunidade através de murais pintados nas fachadas das casas. Criado pelos próprios moradores, ele transforma a favela em si num roteiro cultural. Outra forma, digna e viva, de ver o Rio.",
},
{
"name": "Museu do Amanhã",
"fr": "Cette structure blanche aux allures de vaisseau, avancée sur l'eau de la place Mauá, c'est le Musée de Demain, signé par l'architecte Santiago Calatrava en 2015. Ce n'est pas un musée d'objets mais d'idées : il interroge notre futur — climat, société, cosmos — par des expériences interactives. Le symbole de la renaissance de la zone portuaire.",
"en": "This white, ship-like structure, jutting out over the water at Praça Mauá, is the Museum of Tomorrow, designed by architect Santiago Calatrava in twenty fifteen. It's not a museum of objects but of ideas: it questions our future, climate, society, the cosmos, through interactive experiences. The symbol of the port area's rebirth.",
"es": "Esta estructura blanca con aires de nave, que avanza sobre el agua de la Praça Mauá, es el Museo del Mañana, diseñado por el arquitecto Santiago Calatrava en dos mil quince. No es un museo de objetos sino de ideas: interroga nuestro futuro, clima, sociedad, cosmos, a través de experiencias interactivas. El símbolo del renacimiento de la zona portuaria.",
"pt": "Essa estrutura branca com jeito de nave, avançando sobre a água da Praça Mauá, é o Museu do Amanhã, assinado pelo arquiteto Santiago Calatrava em dois mil e quinze. Não é um museu de objetos, mas de ideias: ele questiona nosso futuro, clima, sociedade, cosmos, através de experiências interativas. O símbolo do renascimento da zona portuária.",
},
{
"name": "Planetário da Gávea",
"fr": "Dans le quartier de la Gávea, ce complexe réunit des coupoles de projection, un musée de l'univers et des télescopes ouverts au public certains soirs. Parfait pour une sortie en famille ou une pause science entre deux plages, avec des séances d'observation du ciel carioca à la tombée de la nuit.",
"en": "In the Gávea neighborhood, this complex brings together projection domes, a museum of the universe, and telescopes open to the public on certain evenings. Perfect for a family outing or a science break between beach visits, with sky-watching sessions of the carioca sky at nightfall.",
"es": "En el barrio de Gávea, este complejo reúne cúpulas de proyección, un museo del universo y telescopios abiertos al público algunas noches. Perfecto para una salida en familia o una pausa científica entre dos playas, con sesiones de observación del cielo carioca al caer la noche.",
"pt": "No bairro da Gávea, esse complexo reúne cúpulas de projeção, um museu do universo e telescópios abertos ao público em algumas noites. Perfeito para um passeio em família ou uma pausa científica entre duas praias, com sessões de observação do céu carioca ao cair da noite.",
},
{
"name": "Cidade das artes",
"fr": "À Barra da Tijuca, ce vaste complexe de béton signé Christian de Portzamparc, surélevé comme une grande terrasse ouverte, abrite l'une des plus grandes salles de concert symphonique et d'opéra d'Amérique latine, ainsi qu'un théâtre de chambre et une salle électroacoustique. Le grand pôle culturel de l'ouest de Rio, pensé comme une place publique suspendue.",
"en": "In Barra da Tijuca, this vast concrete complex designed by Christian de Portzamparc, raised up like a great open terrace, houses one of the largest symphonic and opera concert halls in Latin America, along with a chamber theater and an electroacoustic hall. The major cultural hub of western Rio, conceived as a suspended public square.",
"es": "En Barra da Tijuca, este vasto complejo de concreto diseñado por Christian de Portzamparc, elevado como una gran terraza abierta, alberga una de las mayores salas de concierto sinfónico y de ópera de América Latina, además de un teatro de cámara y una sala electroacústica. El gran polo cultural del oeste de Río, pensado como una plaza pública suspendida.",
"pt": "Na Barra da Tijuca, esse vasto complexo de concreto assinado por Christian de Portzamparc, elevado como um grande terraço aberto, abriga uma das maiores salas de concerto sinfônico e de ópera da América Latina, além de um teatro de câmara e uma sala eletroacústica. O grande polo cultural da zona oeste do Rio, pensado como uma praça pública suspensa.",
},
{
"name": "Circo Voador",
"fr": "Sous sa toile tendue au pied des Arcos da Lapa, le Circo Voador est une salle mythique de la musique brésilienne depuis les années 1980. De nombreux grands noms y ont débuté. Intime et bouillonnante, c'est l'adresse à connaître pour une nuit de concert au cœur de la Lapa.",
"en": "Under its stretched tent canvas at the foot of the Arcos da Lapa, the Circo Voador has been a legendary Brazilian music venue since the nineteen eighties. Many big names got their start here. Intimate and buzzing, it's the place to know for a night of live music in the heart of Lapa.",
"es": "Bajo su lona tensada al pie de los Arcos da Lapa, el Circo Voador es una sala mítica de la música brasileña desde los años mil novecientos ochenta. Muchos grandes nombres debutaron aquí. Íntimo y bullicioso, es el lugar que hay que conocer para una noche de concierto en el corazón de la Lapa.",
"pt": "Sob sua lona esticada aos pés dos Arcos da Lapa, o Circo Voador é uma casa mítica da música brasileira desde os anos mil novecentos e oitenta. Muitos grandes nomes estrearam ali. Intimista e fervilhante, é o endereço certo para uma noite de show no coração da Lapa.",
},
{
"name": "Theatro Municipal",
"fr": "Inauguré en 1909, le Théâtre municipal de Rio est situé sur la place de la Cinelândia. Feuilles d'or, cuivre, vitraux et sculptures : tout ici dit l'ambition d'une ville qui se rêvait capitale des arts. Opéra, ballet et concerts s'y donnent encore aujourd'hui.",
"en": "Opened in nineteen-oh-nine, Rio's Theatro Municipal stands on Cinelândia square. Gold leaf, copper, stained glass, and sculptures: everything here speaks of the ambition of a city that dreamed of becoming a capital of the arts. Opera, ballet, and concerts are still performed here today.",
"es": "Inaugurado en mil novecientos nueve, el Teatro Municipal de Río se encuentra en la plaza de la Cinelândia. Pan de oro, cobre, vitrales y esculturas: todo aquí habla de la ambición de una ciudad que se soñaba capital de las artes. Ópera, ballet y conciertos todavía se presentan aquí hoy.",
"pt": "Inaugurado em mil novecentos e nove, o Theatro Municipal do Rio fica na praça da Cinelândia. Folhas de ouro, cobre, vitrais e esculturas: tudo aqui fala da ambição de uma cidade que se sonhava capital das artes. Ópera, balé e concertos ainda acontecem ali hoje.",
},
]
