# -*- coding: utf-8 -*-
# Adaptations multilingues (EN/ES/PT-BR) des narrations FR — partie 1/4
# Générées en suivant le prompt system : fidélité aux faits, registre oral,
# durée équivalente, noms propres non traduits, adaptation culturelle par langue.

DATA_PART1 = [
{
"name": "Casa França-Brasil",
"fr": "Ce bâtiment néoclassique de 1820, dessiné par l'architecte français Grandjean de Montigny, fut la première halle de style européen de Rio. Sa nef à colonnes, inspirée d'un temple antique, en fait un espace d'exposition à l'acoustique remarquable. Un témoin de la mission artistique française venue moderniser la jeune capitale impériale.",
"en": "This eighteen-twenty neoclassical building, designed by French architect Grandjean de Montigny, was Rio's first European-style market hall. Its columned nave, inspired by an ancient temple, makes it an exhibition space with remarkable acoustics. A witness to the French artistic mission that came to modernize the young imperial capital.",
"es": "Este edificio neoclásico de mil ochocientos veinte, diseñado por el arquitecto francés Grandjean de Montigny, fue el primer mercado de estilo europeo de Río. Su nave de columnas, inspirada en un templo antiguo, lo convierte en un espacio de exposiciones de acústica notable. Un testigo de la misión artística francesa que vino a modernizar la joven capital imperial.",
"pt": "Este prédio neoclássico de mil oitocentos e vinte, projetado pelo arquiteto francês Grandjean de Montigny, foi o primeiro mercado em estilo europeu do Rio. Sua nave de colunas, inspirada em um templo antigo, faz dele um espaço de exposições com acústica notável. Uma testemunha da missão artística francesa que veio modernizar a jovem capital imperial.",
},
{
"name": "Chácara do Céu",
"fr": "Sur les hauteurs de Santa Teresa, cette ancienne demeure moderniste abrite la collection d'un grand mécène : maîtres européens, art brésilien, objets précieux. Mais on y vient aussi pour le jardin et sa vue imprenable sur le centre et la baie. Petit musée, grand charme.",
"en": "High up in Santa Teresa, this former modernist residence houses a great patron's collection: European masters, Brazilian art, precious objects. But people also come for the garden and its sweeping view over downtown and the bay. A small museum with great charm.",
"es": "En las alturas de Santa Teresa, esta antigua residencia modernista alberga la colección de un gran mecenas: maestros europeos, arte brasileño, objetos preciosos. Pero también se viene por el jardín y su vista impresionante sobre el centro y la bahía. Un museo pequeño, un gran encanto.",
"pt": "No alto de Santa Teresa, esta antiga residência modernista abriga a coleção de um grande mecenas: mestres europeus, arte brasileira, objetos preciosos. Mas também se vem pelo jardim e sua vista de tirar o fôlego sobre o centro e a baía. Um museu pequeno, um charme enorme.",
},
{
"name": "Museu Casa do Pontal",
"fr": "À l'ouest de la ville, ce musée abrite la plus grande collection d'art populaire brésilien : des milliers de figurines et de scènes sculptées par des artistes de tout le pays. Coloré, vivant et méconnu, il plonge dans l'imaginaire du peuple brésilien. Le détour en vaut la peine.",
"en": "In the west of the city, this museum holds the largest collection of Brazilian folk art: thousands of figurines and carved scenes made by artists from all over the country. Colorful, lively, and little known, it dives into the imagination of the Brazilian people. Well worth the detour.",
"es": "Al oeste de la ciudad, este museo alberga la mayor colección de arte popular brasileño: miles de figuras y escenas talladas por artistas de todo el país. Colorido, vivo y poco conocido, se sumerge en el imaginario del pueblo brasileño. Vale la pena el desvío.",
"pt": "A oeste da cidade, este museu abriga a maior coleção de arte popular brasileira: milhares de bonecos e cenas esculpidas por artistas de todo o país. Colorido, vivo e pouco conhecido, ele mergulha no imaginário do povo brasileiro. Vale muito o desvio.",
},
{
"name": "Museu de Arte do Rio (MAR)",
"fr": "Sur la Praça Mauá, le MAR réunit deux bâtiments que tout oppose — un palais éclectique et une structure moderne — coiffés d'une même toiture ondulée. Ouvert en 2013, il explore Rio par l'art : la ville, ses habitants, ses contrastes. Sur le toit, une belle vue sur le port réhabilité et le Musée de Demain voisin.",
"en": "On Praça Mauá, the MAR joins two buildings that couldn't be more different, an eclectic palace and a modern structure, topped by the same wave-shaped roof. Opened in twenty thirteen, it explores Rio through art: the city, its people, its contrasts. From the rooftop, a lovely view over the redeveloped port and the neighboring Museum of Tomorrow.",
"es": "En la Praça Mauá, el MAR une dos edificios completamente opuestos, un palacio ecléctico y una estructura moderna, coronados por el mismo techo ondulado. Inaugurado en dos mil trece, explora Río a través del arte: la ciudad, sus habitantes, sus contrastes. Desde la azotea, una hermosa vista sobre el puerto renovado y el vecino Museo del Mañana.",
"pt": "Na Praça Mauá, o MAR reúne dois prédios completamente opostos, um palacete eclético e uma estrutura moderna, cobertos pelo mesmo telhado ondulado. Aberto em dois mil e treze, ele explora o Rio através da arte: a cidade, seus moradores, seus contrastes. Do telhado, uma bela vista para o porto revitalizado e o vizinho Museu do Amanhã.",
},
{
"name": "Polo Praça XV",
"fr": "Cœur historique de Rio, cette place ouverte sur la baie accueillit l'arrivée de la cour portugaise en 1808. Autour, le Paço Imperial, l'Arco do Teles et l'embarcadère des ferries pour Niterói et Paquetá. Le week-end, une foire d'antiquités l'anime. C'est ici, littéralement, que l'histoire du Brésil moderne a commencé.",
"en": "The historic heart of Rio, this square opening onto the bay welcomed the arrival of the Portuguese royal court in eighteen-oh-eight. Around it stand the Paço Imperial, the Arco do Teles, and the ferry terminal to Niterói and Paquetá. On weekends, an antiques fair brings it to life. This is, quite literally, where modern Brazilian history began.",
"es": "Corazón histórico de Río, esta plaza abierta a la bahía recibió la llegada de la corte portuguesa en mil ochocientos ocho. Alrededor, el Paço Imperial, el Arco do Teles y el embarcadero de los ferris hacia Niterói y Paquetá. Los fines de semana, una feria de antigüedades la anima. Aquí, literalmente, comenzó la historia del Brasil moderno.",
"pt": "Coração histórico do Rio, esta praça aberta para a baía recebeu a chegada da corte portuguesa em mil oitocentos e oito. Ao redor, o Paço Imperial, o Arco do Teles e o embarque das barcas para Niterói e Paquetá. Aos fins de semana, uma feira de antiguidades a anima. É aqui, literalmente, que a história do Brasil moderno começou.",
},
{
"name": "Praia de Botafogo",
"fr": "Cette plage en croissant, tournée vers l'intérieur de la baie, offre l'une des cartes postales les plus célèbres de Rio : les voiliers de la marina au premier plan, le Pain de Sucre en fond. On ne s'y baigne guère, mais on y vient au coucher du soleil pour la vue, imbattable.",
"en": "This crescent-shaped beach, facing toward the inner curve of the bay, offers one of Rio's most famous postcard views: the marina's sailboats in the foreground, Sugarloaf Mountain rising behind them. Hardly anyone swims here, but people come at sunset just for the view, and it truly is unbeatable.",
"es": "Esta playa en forma de media luna, orientada hacia el interior de la bahía, ofrece una de las postales más famosas de Río: los veleros de la marina en primer plano, el Pan de Azúcar al fondo. Casi nadie se baña aquí, pero todos vienen al atardecer por la vista, inigualable.",
"pt": "Essa praia em formato de meia-lua, voltada para dentro da baía, oferece um dos cartões-postais mais famosos do Rio: os veleiros da marina em primeiro plano, o Pão de Açúcar ao fundo. Quase ninguém entra na água aqui, mas todo mundo vem ao pôr do sol pela vista, imbatível.",
},
{
"name": "Praia de Copacabana",
"fr": "Un long arc de sable blanc bordé par la fameuse promenade en vagues noires et blanches dessinée par Roberto Burle Marx. Copacabana, c'est la plage-monde : vendeurs de maté, foot-volley, et un réveillon rassemblant des millions de personnes. Tôt le matin ou en fin de journée, marchez-y simplement : c'est là que bat le pouls de Rio.",
"en": "A long arc of white sand bordered by the famous black-and-white wave-pattern promenade designed by Roberto Burle Marx. Copacabana is the world's beach: maté vendors, footvolley games, and a New Year's Eve gathering millions of people. Early morning or late afternoon, just walk along it, this is where Rio's pulse beats.",
"es": "Un largo arco de arena blanca bordeado por el famoso paseo de olas en blanco y negro diseñado por Roberto Burle Marx. Copacabana es la playa-mundo: vendedores de mate, fútbol-vóley y una Nochevieja que reúne a millones de personas. Temprano en la mañana o al final del día, simplemente camine por ella: aquí late el pulso de Río.",
"pt": "Um longo arco de areia branca margeado pelo famoso calçadão de ondas em preto e branco desenhado por Roberto Burle Marx. Copacabana é a praia do mundo: vendedores de mate, futevôlei, e um réveillon que reúne milhões de pessoas. De manhã cedo ou no fim da tarde, basta caminhar por ela: é ali que bate o coração do Rio.",
},
{
"name": "Praia de Ipanema",
"fr": "Immortalisée par la chanson « Garota de Ipanema », cette plage élégante est le rendez-vous branché de Rio. Chaque tronçon, repéré par un poste de secours, a sa tribu. Au coucher du soleil, tout le monde se tourne vers le Morro Dois Irmãos et applaudit le dernier rayon. Une tradition à vivre au moins une fois.",
"en": "Made famous by the song 'The Girl from Ipanema', this elegant beach is Rio's trendiest gathering spot. Each stretch, marked by a lifeguard post, has its own crowd. At sunset, everyone turns toward the Morro Dois Irmãos and applauds the last ray of light. A tradition worth experiencing at least once.",
"es": "Inmortalizada por la canción 'Garota de Ipanema', esta elegante playa es el punto de encuentro más de moda de Río. Cada tramo, marcado por un puesto de guardavidas, tiene su propia tribu. Al atardecer, todos se giran hacia el Morro Dois Irmãos y aplauden el último rayo de sol. Una tradición que vale la pena vivir al menos una vez.",
"pt": "Eternizada pela música 'Garota de Ipanema', essa praia elegante é o point mais descolado do Rio. Cada trecho, marcado por um posto de salva-vidas, tem sua turma. No pôr do sol, todo mundo se vira pro Morro Dois Irmãos e aplaude o último raio de sol. Uma tradição pra viver pelo menos uma vez.",
},
{
"name": "Praia do Arpoador",
"fr": "Entre Copacabana et Ipanema, ce promontoire rocheux est LE spot du coucher de soleil à Rio. Chaque soir, la foule s'y masse et applaudit le soleil qui plonge derrière le Morro Dois Irmãos. En contrebas, une petite plage prisée des surfeurs. Gratuit, magique, incontournable.",
"en": "Between Copacabana and Ipanema, this rocky headland is THE sunset spot in Rio. Every evening, crowds gather and applaud as the sun dips behind the Morro Dois Irmãos. Below, a small beach popular with surfers. Free, magical, unmissable.",
"es": "Entre Copacabana e Ipanema, este promontorio rocoso es EL lugar para ver el atardecer en Río. Cada noche, la multitud se reúne y aplaude cuando el sol se hunde detrás del Morro Dois Irmãos. Más abajo, una pequeña playa muy querida por los surfistas. Gratis, mágico, imperdible.",
"pt": "Entre Copacabana e Ipanema, esse promontório rochoso é O point do pôr do sol no Rio. Toda noite, a multidão se reúne e aplaude o sol mergulhando atrás do Morro Dois Irmãos. Lá embaixo, uma praiazinha querida pelos surfistas. De graça, mágico, imperdível.",
},
{
"name": "Praia do Leblon",
"fr": "Prolongement plus tranquille et chic d'Ipanema, le Leblon est la plage des familles et des cariocas du quartier. À son extrémité, le mirante offre une belle vue sur le sable et les Deux Frères. Ambiance plus posée, cafés et bars raffinés juste derrière la plage.",
"en": "A quieter, more upscale extension of Ipanema, Leblon is the beach for families and local cariocas. At its far end, a lookout point offers a lovely view over the sand and the Dois Irmãos hills. A calmer atmosphere, with refined cafés and bars just behind the beach.",
"es": "Extensión más tranquila y elegante de Ipanema, Leblon es la playa de las familias y de los cariocas del barrio. En su extremo, el mirador ofrece una hermosa vista sobre la arena y los Dos Hermanos. Ambiente más relajado, cafés y bares refinados justo detrás de la playa.",
"pt": "Extensão mais tranquila e chique de Ipanema, o Leblon é a praia das famílias e dos cariocas do bairro. Na sua ponta, o mirante oferece uma bela vista da areia e do Dois Irmãos. Clima mais tranquilo, cafés e bares refinados logo atrás da praia.",
},
{
"name": "Instituto De Pesquisas Jardim Botânico Do Rio De Janeiro",
"fr": "Créé en 1808 par le prince régent Dom João, ce jardin botanique fut d'abord un jardin d'acclimatation pour les épices. On y déambule parmi des milliers d'espèces, sous la célèbre allée de palmiers impériaux hauts de plus de trente mètres. Orchidées, nénuphars géants et petits singes tití : une oasis au pied du Corcovado.",
"en": "Created in eighteen-oh-eight by Prince Regent Dom João, this botanical garden began as an acclimatization garden for spices. You wander among thousands of species, beneath the famous avenue of imperial palms over thirty meters tall. Orchids, giant water lilies, and little tití monkeys: an oasis at the foot of the Corcovado.",
"es": "Creado en mil ochocientos ocho por el príncipe regente Dom João, este jardín botánico fue primero un jardín de aclimatación para especias. Se pasea entre miles de especies, bajo la célebre alameda de palmeras imperiales de más de treinta metros de altura. Orquídeas, nenúfares gigantes y pequeños monos tití: un oasis al pie del Corcovado.",
"pt": "Criado em mil oitocentos e oito pelo príncipe regente Dom João, este jardim botânico foi primeiro um jardim de aclimatação de especiarias. Passeia-se entre milhares de espécies, sob a famosa aleia de palmeiras imperiais com mais de trinta metros de altura. Orquídeas, vitórias-régias e micos pequenos: um oásis ao pé do Corcovado.",
},
{
"name": "Sítio Roberto Burle Marx",
"fr": "À l'ouest de la ville, l'ancienne propriété du paysagiste Roberto Burle Marx est un jardin-œuvre d'art : des milliers d'espèces tropicales, dont beaucoup qu'il a lui-même sauvées de l'oubli, composées comme un tableau vivant. Classé au patrimoine mondial de l'UNESCO en 2021. La visite se fait sur réservation — un enchantement pour qui aime les plantes.",
"en": "In the west of the city, landscape architect Roberto Burle Marx's former estate is a living work of art: thousands of tropical species, many of which he personally saved from oblivion, arranged like a living painting. Named a UNESCO World Heritage Site in twenty twenty-one. Visits are by reservation only, a delight for anyone who loves plants.",
"es": "Al oeste de la ciudad, la antigua propiedad del paisajista Roberto Burle Marx es un jardín-obra de arte: miles de especies tropicales, muchas de las cuales él mismo salvó del olvido, dispuestas como un cuadro vivo. Declarado Patrimonio Mundial de la UNESCO en dos mil veintiuno. La visita se hace con reserva previa, un encanto para quien ama las plantas.",
"pt": "A oeste da cidade, a antiga propriedade do paisagista Roberto Burle Marx é um jardim-obra de arte: milhares de espécies tropicais, muitas das quais ele mesmo salvou do esquecimento, dispostas como um quadro vivo. Tombado como Patrimônio Mundial da UNESCO em dois mil e vinte e um. A visita é feita com reserva, um encanto para quem ama plantas.",
},
{
"name": "Centro Cultural Banco do Brasil (Rio de Janeiro)",
"fr": "Ancien siège de la Banque du Brésil, ce palais de 1906 à la rotonde monumentale est devenu l'un des centres culturels les plus fréquentés du pays. Expositions internationales, cinéma, théâtre, concerts, souvent gratuits. Prenez le temps de lever les yeux vers la verrière et l'escalier de fer. L'entrée est libre : profitez-en.",
"en": "Once the headquarters of the Bank of Brazil, this nineteen-oh-six palace with its monumental rotunda has become one of the country's most visited cultural centers. International exhibitions, film, theater, concerts, often free. Take a moment to look up at the glass roof and the iron staircase. Admission is free, so make the most of it.",
"es": "Antigua sede del Banco de Brasil, este palacio de mil novecientos seis con su rotonda monumental se ha convertido en uno de los centros culturales más visitados del país. Exposiciones internacionales, cine, teatro, conciertos, a menudo gratuitos. Tómese un momento para mirar hacia el techo de vidrio y la escalera de hierro. La entrada es gratuita, aprovéchela.",
"pt": "Antiga sede do Banco do Brasil, este palacete de mil novecentos e seis com sua rotunda monumental se tornou um dos centros culturais mais visitados do país. Exposições internacionais, cinema, teatro, shows, muitas vezes gratuitos. Reserve um tempo para olhar para cima, para a claraboia e a escada de ferro. A entrada é gratuita, aproveite.",
},
{
"name": "Centro Cultural Correios",
"fr": "Dans un élégant bâtiment du début du XXe siècle, ce centre culturel de la Poste propose expositions et concerts, souvent gratuits. Avec le CCBB et la Casa França-Brasil tout proches, il forme le « couloir culturel » du centre historique — trois grands lieux à enchaîner à pied en une après-midi.",
"en": "In an elegant early-twentieth-century building, this post office cultural center hosts exhibitions and concerts, often free. Together with the nearby CCBB and Casa França-Brasil, it forms the historic center's 'cultural corridor', three great venues you can walk between in one afternoon.",
"es": "En un elegante edificio de principios del siglo veinte, este centro cultural de Correos ofrece exposiciones y conciertos, a menudo gratuitos. Junto con el cercano CCBB y la Casa França-Brasil, forma el 'corredor cultural' del centro histórico, tres grandes lugares que se pueden recorrer a pie en una tarde.",
"pt": "Em um elegante prédio do início do século vinte, esse centro cultural dos Correios oferece exposições e shows, muitas vezes gratuitos. Junto com o CCBB e a Casa França-Brasil ali pertinho, ele forma o 'corredor cultural' do centro histórico, três grandes espaços pra emendar a pé numa tarde só.",
},
{
"name": "Centro Cultural Fundição Progresso",
"fr": "Ancienne fonderie devenue haut lieu culturel de la Lapa, la Fundição Progresso accueille concerts, cirque, danse et ateliers. Avec le Circo Voador voisin, elle est le cœur battant de la scène artistique alternative de Rio. Un soir de spectacle, tout le quartier vibre au son de la samba et du rock.",
"en": "A former foundry turned cultural landmark in Lapa, the Fundição Progresso hosts concerts, circus shows, dance, and workshops. Along with the neighboring Circo Voador, it's the beating heart of Rio's alternative arts scene. On a show night, the whole neighborhood vibrates to the sound of samba and rock.",
"es": "Antigua fundición convertida en un gran centro cultural de la Lapa, la Fundição Progresso acoge conciertos, circo, danza y talleres. Junto con el vecino Circo Voador, es el corazón palpitante de la escena artística alternativa de Río. En una noche de espectáculo, todo el barrio vibra al son de la samba y el rock.",
"pt": "Antiga fundição que virou point cultural da Lapa, a Fundição Progresso recebe shows, circo, dança e oficinas. Junto com o vizinho Circo Voador, é o coração pulsante da cena artística alternativa do Rio. Numa noite de show, o bairro inteiro vibra ao som de samba e rock.",
},
{
"name": "Centro Cultural Municipal Parque das Ruínas",
"fr": "Sur les hauteurs de Santa Teresa, ce sont les ruines d'un manoir ayant appartenu à une riche mécène, où se réunissait l'élite artistique du début du XXe siècle. Restaurées et coiffées d'une structure moderne, elles accueillent expositions et concerts. Mais on y monte surtout pour la terrasse : une vue panoramique sur le centre et la baie.",
"en": "High up in Santa Teresa, these are the ruins of a mansion once owned by a wealthy patron, where the artistic elite of the early twentieth century used to gather. Restored and topped with a modern structure, it now hosts exhibitions and concerts. But people mostly come up for the terrace, a panoramic view over downtown and the bay.",
"es": "En las alturas de Santa Teresa, estas son las ruinas de una mansión que perteneció a una rica mecenas, donde se reunía la élite artística de principios del siglo veinte. Restauradas y coronadas por una estructura moderna, hoy acogen exposiciones y conciertos. Pero se sube sobre todo por la terraza, una vista panorámica sobre el centro y la bahía.",
"pt": "No alto de Santa Teresa, essas são as ruínas de uma mansão que pertenceu a uma rica mecenas, onde se reunia a elite artística do início do século vinte. Restauradas e cobertas por uma estrutura moderna, hoje recebem exposições e shows. Mas a gente sobe mesmo é pelo terraço, uma vista panorâmica sobre o centro e a baía.",
},
{
"name": "Feira de São Cristóvão",
"fr": "Sous une grande halle circulaire, cette foire est le cœur battant de la culture du Nordeste à Rio : des centaines de stands de cuisine, d'artisanat et de musique, avec du forró en live jusqu'au bout de la nuit le week-end. Son vrai nom : le Centre Luiz Gonzaga des traditions nordestines. Venez le ventre vide.",
"en": "Under a great circular hall, this fair is the beating heart of Northeastern Brazilian culture in Rio: hundreds of food, craft, and music stalls, with live forró music until dawn on weekends. Its real name: the Luiz Gonzaga Center for Northeastern Traditions. Come with an empty stomach.",
"es": "Bajo un gran pabellón circular, esta feria es el corazón palpitante de la cultura del Nordeste en Río: cientos de puestos de comida, artesanía y música, con forró en vivo hasta el amanecer los fines de semana. Su verdadero nombre: el Centro Luiz Gonzaga de las Tradiciones Nordestinas. Venga con el estómago vacío.",
"pt": "Sob um grande pavilhão circular, essa feira é o coração pulsante da cultura nordestina no Rio: centenas de barracas de comida, artesanato e música, com forró ao vivo até altas horas nos fins de semana. Seu verdadeiro nome: Centro Luiz Gonzaga de Tradições Nordestinas. Venha de estômago vazio.",
},
{
"name": "Instituto Moreira Salles (IMS Rio)",
"fr": "Dans un beau bâtiment moderniste de la Gávea, ce centre culturel privé est une référence pour la photographie et les arts au Brésil. Expositions soignées, jardins signés Burle Marx, librairie et café : une parenthèse raffinée, souvent gratuite, à l'écart des circuits touristiques.",
"en": "In a beautiful modernist building in Gávea, this private cultural center is a leading name in photography and the arts in Brazil. Carefully curated exhibitions, gardens designed by Burle Marx, a bookshop and café: a refined pause, often free, away from the tourist trail.",
"es": "En un hermoso edificio modernista de Gávea, este centro cultural privado es una referencia de la fotografía y las artes en Brasil. Exposiciones cuidadas, jardines firmados por Burle Marx, librería y café: un paréntesis refinado, a menudo gratuito, alejado de las rutas turísticas.",
"pt": "Em um belo prédio modernista da Gávea, esse centro cultural privado é referência em fotografia e artes no Brasil. Exposições cuidadosas, jardins assinados por Burle Marx, livraria e café: uma pausa refinada, muitas vezes gratuita, longe dos roteiros turísticos.",
},
{
"name": "Paço Imperial",
"fr": "Sur la Praça XV, ce sobre édifice colonial fut le siège du pouvoir : résidence des gouverneurs, puis des rois et empereurs. C'est de son balcon que la princesse Isabel proclama, en 1888, l'abolition de l'esclavage — la Loi d'Or. Restauré, il abrite aujourd'hui expositions et cinéma. Un bâtiment discret qui a vu naître un pays.",
"en": "On Praça XV, this understated colonial building was once the seat of power: home to governors, then to kings and emperors. It was from its balcony that Princess Isabel proclaimed the abolition of slavery in eighteen eighty-eight, the Golden Law. Restored, it now hosts exhibitions and film screenings. An unassuming building that watched a nation being born.",
"es": "En la Praça XV, este sobrio edificio colonial fue sede del poder: residencia de gobernadores y luego de reyes y emperadores. Fue desde su balcón que la princesa Isabel proclamó, en mil ochocientos ochenta y ocho, la abolición de la esclavitud, la Ley Áurea. Restaurado, hoy alberga exposiciones y cine. Un edificio discreto que vio nacer un país.",
"pt": "Na Praça XV, esse sóbrio prédio colonial foi sede do poder: residência de governadores, depois de reis e imperadores. Foi de sua sacada que a princesa Isabel proclamou, em mil oitocentos e oitenta e oito, a abolição da escravidão, a Lei Áurea. Restaurado, hoje abriga exposições e cinema. Um prédio discreto que viu nascer um país.",
},
{
"name": "Samba da Pedra do Sal",
"fr": "Ici, dans l'ancienne « Petite Afrique » de Rio, vivaient et débarquaient des Africains réduits en esclavage. C'est sur ces pavés qu'est né le samba tel qu'on le connaît. Aujourd'hui, la Pedra do Sal est un haut lieu de mémoire noire et un rendez-vous de roda de samba en plein air, les lundis et vendredis soir. Un morceau d'âme et d'histoire.",
"en": "Here, in what was once Rio's 'Little Africa', enslaved Africans lived and were brought ashore. It was on these very cobblestones that samba, as we know it, was born. Today, Pedra do Sal is a major site of Black memory and an open-air samba roda gathering, on Monday and Friday nights. A piece of soul and history.",
"es": "Aquí, en la antigua 'Pequeña África' de Río, vivían y desembarcaban africanos esclavizados. Fue sobre estos adoquines que nació el samba tal como lo conocemos. Hoy, la Pedra do Sal es un lugar clave de la memoria negra y punto de encuentro de rodas de samba al aire libre, los lunes y viernes por la noche. Un pedazo de alma e historia.",
"pt": "Aqui, na antiga 'Pequena África' do Rio, viviam e desembarcavam africanos escravizados. Foi nessas pedras que nasceu o samba como a gente conhece. Hoje, a Pedra do Sal é um lugar forte de memória negra e ponto de roda de samba a céu aberto, nas segundas e sextas à noite. Um pedaço de alma e de história.",
},
]
